@bcc -ml -I..\include SCRDEMO1.C common.c ..\lib\*.lib
@bcc -ml -I..\include SCRDEMO2.C common.c ..\lib\*.lib
@bcc -ml -I..\include SCRDEMO3.C common.c ..\lib\*.lib
@bcc -ml -I..\include SDEMO1-1.C common.c ..\lib\*.lib
@bcc -ml -I..\include SDEMO1-2.C common.c ..\lib\*.lib
@bcc -ml -I..\include SDEMO1-3.C common.c ..\lib\*.lib
@bcc -ml -I..\include SPRDEMO2.C common.c ..\lib\*.lib
@bcc -ml -I..\include PMDEMO2.C  common.c ..\lib\*.lib
