#ifndef __16COLOR__
#define __16COLOR__

#define BLACK           0x00
#define BLUE            0x01
#define GREEN           0x02
#define CYAN            0x03
#define RED             0x04
#define MAGENTA         0x05
#define BROWN           0x06
#define WHITE           0x07
#define GRAY            0x08
#define LIGHTBLUE       0x09
#define LIGHTGREEN      0x0a
#define LIGHTCYAN       0x0b
#define LIGHTRED        0x0c
#define LIGHTMAGENTA    0x0d
#define YELLOW          0x0e
#define BRIGHTWHITE     0x0f

#endif
