#ifndef __KEYINT__
#define __KEYINT__

#define KEY_NoKey          (0)

#define KEY_F1             (59  + 256)
#define _KEY_F1            KEY_F1
#define KEY_ShiftF1        (84  + 256)
#define KEY_CtrlF1         (94  + 256)
#define KEY_AltF1          (104 + 256)

#define KEY_F2             (60  + 256)
#define _KEY_F2            KEY_F2
#define KEY_ShiftF2        (85  + 256)
#define KEY_CtrlF2         (95  + 256)
#define KEY_AltF2          (105 + 256)

#define KEY_F3             (61  + 256)
#define _KEY_F3            KEY_F3
#define KEY_ShiftF3        (86  + 256)
#define KEY_CtrlF3         (96  + 256)
#define KEY_AltF3          (106 + 256)

#define KEY_F4             (62  + 256)
#define _KEY_F4            KEY_F4
#define KEY_ShiftF4        (87  + 256)
#define KEY_CtrlF4         (97  + 256)
#define KEY_AltF4          (107 + 256)

#define KEY_F5             (63  + 256)
#define _KEY_F5            KEY_F5
#define KEY_ShiftF5        (88  + 256)
#define KEY_CtrlF5         (98  + 256)
#define KEY_AltF5          (108 + 256)

#define KEY_F6             (64  + 256)
#define _KEY_F6            KEY_F6
#define KEY_ShiftF6        (89  + 256)
#define KEY_CtrlF6         (99  + 256)
#define KEY_AltF6          (109 + 256)

#define KEY_F7             (65  + 256)
#define _KEY_F7            KEY_F7
#define KEY_ShiftF7        (90  + 256)
#define KEY_CtrlF7         (100 + 256)
#define KEY_AltF7          (110 + 256)

#define KEY_F8             (66  + 256)
#define _KEY_F8            KEY_F8
#define KEY_ShiftF8        (91  + 256)
#define KEY_CtrlF8         (101 + 256)
#define KEY_AltF8          (111 + 256)

#define KEY_F9             (67  + 256)
#define _KEY_F9            KEY_F9
#define KEY_ShiftF9        (92  + 256)
#define KEY_CtrlF9         (102 + 256)
#define KEY_AltF9          (112 + 256)

#define KEY_F10            (68  + 256)
#define _KEY_F10           KEY_F10
#define KEY_ShiftF10       (93  + 256)
#define KEY_CtrlF10        (103 + 256)
#define KEY_AltF10         (113 + 256)

#define KEY_F11            (133 + 256)
#define _KEY_F11           KEY_F11
#define KEY_ShiftF11       (135 + 256)
#define KEY_CtrlF11        (137 + 256)
#define KEY_AltF11         (139 + 256)
					
#define KEY_F12            (134 + 256)
#define _KEY_F12           KEY_F12
#define KEY_ShiftF12       (136 + 256)
#define KEY_CtrlF12        (138 + 256)
#define KEY_AltF12         (140 + 256)

#define KEY_PadSlash       47
#define _KEY_PadSlash      (53 + 256)
#define KEY_ShiftPadSlash  47
#define KEY_CtrlPadSlash   (149 + 256)
#define KEY_AltPadSlash    (164 + 256)

#define KEY_Home           (71  + 256)
#define _KEY_PAD7          KEY_Home
#define _KEY_Home          KEY_Home
#define KEY_ShiftHome      55
#define KEY_CtrlHome       (119 + 256)
#define KEY_AltHome        (151 + 256)

#define KEY_Up             (72 + 256)
#define _KEY_Up            KEY_Up
#define _KEY_PAD8          KEY_Up
#define KEY_ShiftUp        56
#define KEY_CtrlUp         (141 + 256)
#define KEY_AltUp          (152 + 256)

#define KEY_PgUp           (73  + 256)
#define _KEY_PgUp          KEY_PgUp
#define _KEY_PAD9          KEY_PgUp
#define KEY_ShiftPgUp      57
#define KEY_CtrlPgUp       (132 + 256)
#define KEY_AltPgUp        (153 + 256)

#define KEY_Left           (75  + 256)
#define _KEY_Left          KEY_Left
#define _KEY_PAD4          KEY_Left
#define KEY_ShiftLeft      52
#define KEY_CtrlLeft       (115 + 256)
#define KEY_AltLeft        (155 + 256)

#define KEY_ShiftPad5      53
#define _KEY_PAD5          (76  + 256)
#define KEY_CtrlPad5       (143 + 256)

#define KEY_Right          (77 + 256)
#define _KEY_Right         KEY_Right
#define _KEY_PAD6          KEY_Right
#define KEY_ShiftRight     54
#define KEY_CtrlRight      (116 + 256)
#define KEY_AltRight       (157 + 256)

#define KEY_End            (79 + 256)
#define _KEY_End           KEY_End
#define _KEY_PAD1          KEY_End
#define KEY_ShiftEnd       49
#define KEY_CtrlEnd        (117 + 256)
#define KEY_AltEnd         (159 + 256)

#define KEY_Down           (80 + 256)
#define _KEY_Down          KEY_Down
#define _KEY_PAD2          KEY_Down
#define KEY_ShiftDown      50
#define KEY_CtrlDown       (145 + 256)
#define KEY_AltDown        (160 + 256)

#define KEY_PgDn           (81 + 256)
#define _KEY_PgDn          KEY_PgDn
#define _KEY_PAD3          KEY_PgDn
#define KEY_ShiftPgDn      51
#define KEY_CtrlPgDn       (118 + 256)
#define KEY_AltPgDn        (161 + 256)

#define KEY_Ins            (82 + 256)
#define _KEY_Ins           KEY_Ins
#define _KEY_PAD0          KEY_Ins
#define KEY_ShiftIns       48
#define KEY_CtrlIns        (146 + 256)
#define KEY_AltIns         (162 + 256)

#define KEY_Del            (83  + 256)
#define _KEY_Del           KEY_Del
#define _KEY_PADPeriod     KEY_Del
#define KEY_ShiftDel       46
#define KEY_CtrlDel        (147 + 256)
#define KEY_AltDel         (163 + 256)

#define KEY_Backspace      8
#define _KEY_Backspace     (14  + 256)
#define KEY_CtrlBackspace  127
#define KEY_AltBackspace   (14 + 256)

#define KEY_Tab            9
#define KB_ShiftTab        (15  + 256)
#define KEY_CtrlTab        (148 + 256)
#define KEY_AltTab         (165 + 256)

#define KEY_Enter          13
#define _KEY_Enter         (28  + 256)
#define KEY_ShiftEnter     13
#define KEY_CtrlEnter      10
#define KEY_AltEnter       (166 + 256)

#define _Esc               129

#define KEY_Esc            27
#define _KEY_Esc           (1 + 256)
#define KEY_ShiftEsc       27
#define KEY_CtrlEsc        27
#define KEY_AltEsc         (1 + 256)

#define KEY_Space          32
#define _KEY_Space         (57 + 256)

#define KEY_Quote          39
#define _KEY_Quote         (40 + 256)
#define KEY_ShiftQuote     34

#define KEY_PrtSc          42
#define _KEY_PrtSc         (55  + 256)
#define KEY_ShiftPrtSc     (114 + 256)
#define KEY_CtrlPrtSc      (150 + 256)
#define KEY_AltPrtSc       (55  + 256)

#define KEY_PadPlus        43
#define _KEY_PadPlus       (78  + 256)
#define KEY_CtrlPadPlus    (144 + 256)
#define KEY_AltPadPlus     (78  + 256)

#define KEY_Comma          44
#define _KEY_Comma         (51 + 256)
#define KEY_ShiftComma     60
#define KEY_AltComma       (51 + 256)

#define KEY_Minus          45
#define _KEY_Minus         (12 + 256)
#define KEY_ShiftMinus     95
#define KEY_CtrlMinus      31
#define KEY_AltMinus       (130 + 256)

#define KEY_PadMinus       45
#define _KEY_PadMinus      (74 + 256)
#define KEY_CtrlPadMinus   (142 + 256)
#define KEY_AltPadMinus    (74 + 256)

#define KEY_Period         46
#define _KEY_Period        (52 + 256)
#define KEY_ShiftPeriod    62
#define KEY_AltPeriod      (52 + 256)

#define KEY_Slash          47
#define _KEY_Slash         (53 + 256)
#define KEY_ShiftSlash     63
#define KEY_AltSlash       (53 + 256)

#define KEY_0              48
#define _KEY_0             (11 + 256)
#define KEY_Shift0         41
#define KEY_Alt0           (129 + 256)

#define KEY_1              49
#define _KEY_1             (2 + 256)
#define KEY_Shift1         33
#define KEY_Alt1           (120 + 256)

#define KEY_2              50
#define _KEY_2             (3 + 256)
#define KEY_Shift2         64
#define KEY_Alt2           (121 + 256)

#define KEY_3              51
#define _KEY_3             (4 + 256)
#define KEY_Shift3         35
#define KEY_Alt3           (122 + 256)

#define KEY_4              52
#define _KEY_4             (5 + 256)
#define KEY_Shift4         36
#define KEY_Alt4           (123 + 256)

#define KEY_5              53
#define _KEY_5             (6 + 256)
#define KEY_Shift5         37
#define KEY_Alt5           (124 + 256)

#define KEY_6              54
#define _KEY_6             (7 + 256)
#define KEY_Shift6         94
#define KEY_Alt6           (125 + 256)

#define KEY_7              55
#define _KEY_7             (8 + 256)
#define KEY_Shift7         38
#define KEY_Alt7           (126 + 256)

#define KEY_8              56
#define _KEY_8             (9 + 256)
#define KEY_Shift8         42
#define KEY_Alt8           (127 + 256)

#define KEY_9              57
#define _KEY_9             (10 + 256)
#define KEY_Shift9         40
#define KEY_Alt9           (128 + 256)

#define KEY_Semicolon      59
#define _KEY_Semicolon     (40 + 256)
#define KEY_ShiftSemicolon 58
#define KEY_AltSemicolon   (39 + 256)

#define KEY_Equal          61
#define _KEY_Equal         (13 + 256)
#define KEY_ShiftEqual     43
#define KEY_AltEqual       (131 + 256)

#define KEY_A              97
#define _KEY_A             (30 + 256)
#define KEY_ShiftA         65
#define KEY_CtrlA          1
#define KEY_AltA           (30 + 256)

#define KEY_B              98
#define _KEY_B             (48 + 256)
#define KEY_ShiftB         66
#define KEY_CtrlB          2
#define KEY_AltB           (48 + 256)

#define KEY_C              99
#define _KEY_C             (46 + 256)
#define KEY_ShiftC         67
#define KEY_CtrlC          3
#define KEY_AltC           (46 + 256)

#define KEY_D              100
#define _KEY_D             (32 + 256)
#define KEY_ShiftD         68
#define KEY_CtrlD          4
#define KEY_AltD           (32 + 256)

#define KEY_E              101
#define _KEY_E             (18 + 256)
#define KEY_ShiftE         69
#define KEY_CtrlE          5
#define KEY_AltE           (18 + 256)

#define KEY_F              102
#define _KEY_F             (33 + 256)
#define KEY_ShiftF         70
#define KEY_CtrlF          6
#define KEY_AltF           (33 + 256)

#define KEY_G              103
#define _KEY_G             (34 + 256)
#define KEY_ShiftG         71
#define KEY_CtrlG          7
#define KEY_AltG           (34 + 256)

#define KEY_H              104
#define _KEY_H             (35 + 256)
#define KEY_ShiftH         72
#define KEY_CtrlH          8
#define KEY_AltH           (35 + 256)

#define KEY_I              105
#define _KEY_I             (23 + 256)
#define KEY_ShiftI         73
#define KEY_CtrlI          9
#define KEY_AltI           (23 + 256)

#define KEY_J              106
#define _KEY_J             (36 + 256)
#define KEY_ShiftJ         74
#define KEY_CtrlJ          10
#define KEY_AltJ           (36 + 256)

#define KEY_K              107
#define _KEY_K             (37 + 256)
#define KEY_ShiftK         75
#define KEY_CtrlK          11
#define KEY_AltK           (37 + 256)

#define KEY_L              108
#define _KEY_L             (38 + 256)
#define KEY_ShiftL         76
#define KEY_CtrlL          12
#define KEY_AltL           (38 + 256)

#define KEY_M              109
#define _KEY_M             (50 + 256)
#define KEY_ShiftM         77
#define KEY_CtrlM          13
#define KEY_AltM           (50 + 256)

#define KEY_N              110
#define _KEY_N             (49 + 256)
#define KEY_ShiftN         78
#define KEY_CtrlN          14
#define KEY_AltN           (49 + 256)

#define KEY_O              111
#define _KEY_O             (24 + 256)
#define KEY_ShiftO         79
#define KEY_CtrlO          15
#define KEY_AltO           (24 + 256)

#define KEY_P              112
#define _KEY_P             (25 + 256)
#define KEY_ShiftP         80
#define KEY_CtrlP          16
#define KEY_AltP           (25 + 256)

#define KEY_Q              113
#define _KEY_Q             (16 + 256)
#define KEY_ShiftQ         81
#define KEY_CtrlQ          17
#define KEY_AltQ           (16 + 256)

#define KEY_R              114
#define _KEY_R             (19 + 256)
#define KEY_ShiftR         82
#define KEY_CtrlR          18
#define KEY_AltR           (19 + 256)

#define KEY_S              115
#define _KEY_S             (31 + 256)
#define KEY_ShiftS         83
#define KEY_CtrlS          19
#define KEY_AltS           (31 + 256)

#define KEY_T              116
#define _KEY_T             (20 + 256)
#define KEY_ShiftT         84
#define KEY_CtrlT          20
#define KEY_AltT           (20 + 256)

#define KEY_U              117
#define _KEY_U             (22 + 256)
#define KEY_ShiftU         85
#define KEY_CtrlU          21
#define KEY_AltU           (22 + 256)

#define KEY_V              118
#define _KEY_V             (47 + 256)
#define KEY_ShiftV         86
#define KEY_CtrlV          22
#define KEY_AltV           (47 + 256)

#define KEY_W              119
#define _KEY_W             (17 + 256)
#define KEY_ShiftW         87
#define KEY_CtrlW          23
#define KEY_AltW           (17 + 256)

#define KEY_X              120
#define _KEY_X             (45 + 256)
#define KEY_ShiftX         88
#define KEY_CtrlX          24
#define KEY_AltX           (45 + 256)

#define KEY_Y              121
#define _KEY_Y             (21 + 256)
#define KEY_ShiftY         89
#define KEY_CtrlY          25
#define KEY_AltY           (21 + 256)

#define KEY_Z              122
#define _KEY_Z             (44 + 256)
#define KEY_ShiftZ         90
#define KEY_CtrlZ          26
#define KEY_AltZ           (44 + 256)

#define KEY_LeftBracket       91
#define _KEY_LeftBracket      (26 + 256)
#define KEY_ShiftLeftBracket  123
#define KEY_AltLeftBracket    (26 + 256)

#define KEY_RightBracket      93
#define _KEY_RightBracket     (27 + 256)
#define KEY_ShiftRightBracket 125
#define KEY_AltRightBracket   (27 + 256)

#define KEY_BackSlash         92
#define _KEY_BackSlash        (43 + 256)
#define KEY_ShiftBackSlash    124
#define KEY_CtrlBackSlash     28
#define KEY_AltBackSlash      (43 + 256)

#define KEY_BackQuote         96
#define _KEY_BackQuote        (41 + 256)
#define KEY_ShiftBackQuote    126

#define _KEY_Tab              (15 + 256)
#define _KEY_CapsLock         (58 + 256)
#define _KEY_LeftShift        (42 + 256)
#define _KEY_RightShift       (54 + 256)
#define _KEY_Ctrl             (29 + 256)
#define _KEY_Alt              (56 + 256)
#define _KEY_103Hangul        (242)
#define _KEY_103Hanja         (241)
#define _KEY_PrtScr           (55 + 256)
#define _KEY_NumLock          (69 + 256)
#define _KEY_ScrLock          (70 + 256)
#define _KEY_Pause            (69 + 256)

#define KEY_RightShift   0x01
#define KEY_LeftShift    0x02
#define KEY_CtrlShift    0x04
#define KEY_AltShift     0x08
#define KEY_ScrollState  0x10
#define KEY_NumState     0x20
#define KEY_CapsState    0x40
#define KEY_InsState     0x80

#include "common.h"

int  keyPressed( void );
word keyRead( void );
byte keyShiftStatus( void );

void setKbd(void (*event)(int));
void restoreKbd(void);

#endif
